{
 "title": "Users In Time",
 "time": { "from": "2023-06-14T22:00:00.000Z", "to": "2023-06-15T22:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "status", "label": "Status", "query": "All : all, Summary : summary" },
   {
    "name": "subscriptionProductId",
    "label": "Membership",
    "query": "Global : prod_N8Lc8Q5gw9VXRs,Premium : prod_MyyEPECet88fTN, Other : other"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT countryOfResidence, c.name from membersInTime\nLEFT JOIN countries c ON c.code =  countryOfResidence"
   },
   { "name": "city", "label": "City", "query": "SELECT name from cities" }
  ]
 },
 "panels": [
  {
   "title": "Users In Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT toDate(synchronizationDate), COUNT(status), if('${status}'='all', status, CASE\n        WHEN status IN ('guest', 'new', 'awaiting_review', 'approved') THEN 'potential'\n        WHEN status IN ('active', 'paused', 'past_due') THEN 'members'\n        ELSE status\n    END AS groupedStatus)\nFROM \"membersInTime\"\nWHERE IF('${subscriptionProductId}'='all', 1=1, if('${subscriptionProductId}'='other', subscriptionProductId NOT IN ('prod_N8Lc8Q5gw9VXRs', 'prod_MyyEPECet88fTN'), subscriptionProductId='${subscriptionProductId}'))\nAND IF('${country}'='all', 1=1, countryOfResidence='${country}')\nAND IF('${city}'='all', 1=1, arrayExists( i -> (i = '${city}') , secondaryCities))\nGROUP BY toDate(synchronizationDate), if('${status}'='all', status, groupedStatus)\nORDER BY toDate(synchronizationDate)"
    }
   ]
  },
  {
   "title": "Total Potential",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), status\nFROM membersInTime\nWHERE status in ('guest', 'new', 'awaiting_review', 'approved') and toDate(synchronizationDate) = today()\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Total Members",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), status\nFROM membersInTime\nWHERE status in ('active', 'past_due', 'paused') and toDate(synchronizationDate) = today()\nGROUP BY status",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Membership",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), CASE\n        WHEN subscriptionProductId='prod_N8Lc8Q5gw9VXRs' THEN 'Global Membership'\n        WHEN subscriptionProductId='prod_MyyEPECet88fTN' THEN 'Premium House Membership'\n        ELSE 'Other'\n    END AS grouped_subscriptionName\nFROM membersInTime\nWHERE status in ('active', 'past_due', 'paused') AND isNotNull(subscriptionProductName) AND isNotNull(subscriptionProductId) AND toDate(synchronizationDate) = today()\nGROUP BY grouped_subscriptionName"
    }
   ]
  }
 ]
}